---
# See https://pre-commit.com/hooks.html for info on hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: debug-statements
        stages: [commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [commit]
      - id: ruff-format
        stages: [commit]
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: coverage run -m pytest
        stages: [push]
        language: system
        pass_filenames: false
        always_run: true
